### ISSUE TITLE
Please provide binaries for Darwin (amd64,arm64)

### ISSUE THREAD

**Issue by Allaman** [orhun/binsider#10]
I think the title says it all :)

Thanks for your work!

**Comment by orhun** [comment]
Darwin binaries for macOS will be available with the next release! See #31

**Comment by orhun** [comment]
0.2.0 is released.

- Blog post: https://binsider.dev/blog/v020/
- Binaries: https://github.com/orhun/binsider/releases/tag/v0.2.0
