### ISSUE TITLE
Scroll points reset while scrolling

### ISSUE THREAD

**Issue by skunert** [orhun/binsider#19]
While holding the `j` key, I expect long lists to continue scrolling until the key is released.

1. Open a binary with binsider
2. Switch to a view that has a long list of elements (confirmed bug with Strings tab, same with Symbols list)
3. Hold j key to scroll down
4. List shows some kind of pagination behaviour, where from time to time the cursor jumps to the top of the list, but the correct elements stays selected 

**Expected behavior**

I  expected that the cursor stays at the bottom of the list while scrolling.

**Screenshots / Logs**

**Software information**

- Operating system: 6.9.3-76060903-generic x86_64 GNU/Linux
- Rust version: 1.80.0
- Project version: 0.1.0

**Comment by orhun** [comment]
Hello, thanks for the issue!

This is the expected behavior, in fact a workaround, see: https://github.com/ratatui/ratatui/issues/1004

I think it will stay this way until I find a better way of handling this :)
