### ISSUE TITLE
Errors out if creation time not supported

### ISSUE THREAD

**Issue by jgreenbaum** [orhun/binsider#21]
**Describe the bug**

binsider fails to load an elf file from a file system that doesn't support creation. Instead it reports the error "IO error: `creation time is not available for the filesystem`"

**To reproduce**

Run binsider with a file argument on a file system without ctime support, like an NFS mount or tmpfs.

**Expected behavior**

binsider should load the elf file, but not display a creation time

**Software information**

- Operating system: RHEL 8
- Rust version: 1.77.2
- Project version: HEAD

**Additional context**

I worked around it by modifying src/file.rs to set FileDateInfo.birth to "".into() if metadata.created().is_err(). You might want to implement something different.

**Comment by orhun** [comment]
Thanks for the report and sharing your workaround! 

Added a fix here: #25

Do you think there might be other edge cases where e.g. modify or change time is not supported as well? Should we take measures for them as well?

**Comment by sassman** [comment]
I ran into the same issue by running it on docker from an apple silicone machine

```sh
❯ docker run --platform linux/amd64 -v ${PWD}:/mnt -w /mnt --rm -it ubuntu:latest /bin/bash
```

**Comment by orhun** [comment]
Going to be fixed with the upcoming release :)
