### ISSUE TITLE
Nix test failure (test_extract_strings)

### ISSUE THREAD

**Issue by Titaniumtown** [orhun/binsider#27]
**Describe the bug**

The `test_extract_strings` test fails when building from nix.

**To reproduce**

1. Have nix installed
2. run `nix run "github:orhun/binsider"`

**Expected behavior**

It should build and pass all tests

**Screenshots / Logs**
```
running 2 tests
test test_init ... ok
test test_extract_strings ... FAILED

failures:

---- test_extract_strings stdout ----
thread 'test_extract_strings' panicked at tests/app.rs:41:9:
assertion failed: strings?.iter().map(|(s, _)| s).any(|v| v == ".debug_str")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test_extract_strings

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.09s
```

**Software information**

- Operating system: NixOS
- Rust version: 1.77.2 & 1.80.1
- Project version: main

**Comment by Titaniumtown** [comment]
Initial inspection, it works if I clone the repo manually and run `cargo test` (on `1.83.0-nightly (adaff5368 2024-09-12)`)

**Comment by orhun** [comment]
Hello, thanks for the report! 👋🏼 

First of all I really hate that test - we need a better test suite (#5)

Secondly, is there a chance that you are running tests in `--release` mode and that's why `.debug_str` does not exist in the binary?

**Comment by ch4og** [comment]
I had the same issue.
Nix by default runs test in release mode, but after switching to debug mode it still didn't pass checks.

I don't know how cargo and rust work but doing https://github.com/orhun/binsider/pull/30  fixed building for me.

**Comment by Titaniumtown** [comment]
> Hello, thanks for the report! 👋🏼
> 
> First of all I really hate that test - we need a better test suite (#5)
> 
> Secondly, is there a chance that you are running tests in `--release` mode and that's why `.debug_str` does not exist in the binary?

Thank you for your response. I believe nix runs it in test mode. I'll test @ch4og's PR and report back :)
