### ISSUE TITLE
Application fails for platforms where metadata.created() is not supported.

### ISSUE THREAD

**Issue by terjekv** [orhun/binsider#40]
**Describe the bug**

https://github.com/orhun/binsider/blob/fd2f7d2b46b34916009040d78fd6b170728d1338/src/file.rs#L143-L146 uses https://doc.rust-lang.org/std/fs/struct.Metadata.html#method.created to get the created time of the file, but this function supports quite a limited amount of systems and filesystems. xfs/tmpfs/NFS on older kernels and CVMFS as well.

As one example:

```
$ binsider /cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/bin/python
IO error: `creation time is not available for the filesystem`
```

**To reproduce**

Run application on a binary on one of the filesystems above with older kernels (or CVMFS in general).

**Expected behavior**

The application should not abort. In the worst case it should have an empty creation date (or set to some default value).

**Software information**

- Operating system: RHEL8/x86_64 -->
- Project version: 0.1.0 binary from GitHub.

**Comment by orhun** [comment]
Dup: #39 #21 

This was already fixed in #25
