### ISSUE TITLE
Add a (switch|cli-arg) to enable Human Readable Output for `FileSize` `MemSize` `Size`

### ISSUE THREAD

**Issue by Azathothas** [orhun/binsider#47]
Hello,
It would be immensely helpful if there was a switch or a cli option (-h | --human)
This would enable human readable output (KiB,MiB,GiB...) for the hex values of `FileSize` `MemSize` `Size`
Perhaps in the future, this could also be extended to display values other than size in Human readable format.

![image](https://github.com/user-attachments/assets/30798b8d-0974-4c01-b570-02df586db108)
![image](https://github.com/user-attachments/assets/484da994-b333-4f04-9f86-2db195bcdef6)

The intro/summary page already includes a Human readable format:
![image](https://github.com/user-attachments/assets/4eb6ee3b-f9fa-443b-87c2-ae3617204f32)

Note: I don't know much about elf/binary analysis, so I apologize if this request is dumb.
Essentially, I wanted to use binsider to give me a `du|ncdu` kind of output about the size of each section on an elf file.

**Comment by orhun** [comment]
Hello 👋🏼 

Really good suggestion! I currently use the [`bytesize`](https://docs.rs/bytesize) crate to show human readable output for the general tab. It should be fairly straightforward to use it for the other fields as well.

Would you be interested in contributing this feature? I would like to have it available in the upcoming release :)

**Comment by Azathothas** [comment]
Unfortunately, I don't know any rust…
I will wait patiently until that feature is implemented, take your time, there's no rush. :)
