### ISSUE TITLE
Panic when randomly going to next and previous library

### ISSUE THREAD

**Issue by qarmin** [orhun/binsider#59]
**Describe the bug**

When checking random binaries I got this crash
```
^[]11;rgb:1818/1818/1818^[\/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2: missing program name
Try '/usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 --help' for more information.

Backtrace omitted. Run with RUST_BACKTRACE=1 to display it.
Run with RUST_BACKTRACE=full to include source snippets.

The application panicked (crashed).
  failed to send tick event: SendError { .. }
in src/tui/event.rs:80
thread: <unnamed>
```

**To reproduce**

Open random binary
Click randomly enter + backspace
after a while click esc key - probably when "Loading screen is visible"

**Expected behavior**
No crash
**Software information**

- Operating system: 
- Rust version: 1.81.0
- Project version: 3f4f742cfc759425ef767605417ff19d257023f9

**Comment by orhun** [comment]
Hey, thanks for reporting! This is fixed in #62

The issue was, some ANSI escape codes were being run for querying the terminal background on each time you select a dependency. Now we are querying the background color once at the start of the application which should fix this :)
