### ISSUE TITLE
Launch TUI from selected tab

### ISSUE THREAD

**Issue by orhun** [orhun/binsider#6]
**Is your feature request related to a problem? Please describe.**

`binsider` is being started at the "general" tab every time when you close and re-open it.

**Describe the solution you'd like**

It would be nice to add a command-line argument like so:

```sh
binsider --tab static-analysis
```

Or maybe something shorter. Ideas are welcome.

**Describe alternatives you've considered**

Some alternatives are `--menu`, `--method`, ... 🤔 

**Additional context**

None.

**Comment by josueBarretogit** [comment]
Hi can I take this issue?

**Comment by orhun** [comment]
you got it sir!
