### ISSUE TITLE
warning: the following packages contain code that will be rejected by a future version of Rust: bitflags v0.7.0

### ISSUE THREAD

**Issue by ngmisl** [orhun/binsider#61]
future incompatibility warning

**Comment by orhun** [comment]
I don't get this locally. Which platform are you on + what version of Rust are you using?

**Comment by ngmisl** [comment]
The currently active `rustc` version is `rustc 1.81.0 (eeb90cda1 2024-09-04)`
Linux

**Comment by orhun** [comment]
I am able reproduce with `1.81.0` - not sure how to fix this though. I tried `cargo update` but still getting the same warning.

**Comment by cjrh** [comment]
Looks like it comes via lurk-cli

```
├── lurk-cli v0.3.8
│   ├── anyhow v1.0.86
│   ├── atty v0.2.14
│   │   └── libc v0.2.158
│   ├── byteorder v1.5.0
│   ├── clap v4.5.18 (*)
│   ├── comfy-table v7.1.1
│   │   ├── crossterm v0.27.0
│   │   │   ├── bitflags v2.6.0
│   │   │   ├── libc v0.2.158
│   │   │   └── parking_lot v0.12.3 (*)
│   │   ├── strum v0.26.3 (*)
│   │   ├── strum_macros v0.26.4 (proc-macro) (*)
│   │   └── unicode-width v0.1.14
│   ├── console v0.15.8 (*)
│   ├── libc v0.2.158
│   ├── linux-personality v1.0.0
│   │   ├── bitflags v0.7.0                               <--------------- HERE
│   │   └── libc v0.2.158
│   ├── nix v0.29.0
│   │   ├── bitflags v2.6.0
│   │   ├── cfg-if v1.0.0
│   │   └── libc v0.2.158
```

**Comment by TornaxO7** [comment]
And looks like as if [linux-personality](https://github.com/jeandudey/linux-personality) hasn't got any changes for 8 years

**Comment by cjrh** [comment]
That package is quite small and apparently stable, so vendoring could be an option here.

https://github.com/jeandudey/linux-personality/blob/master/src/lib.rs

**Comment by jeandudey** [comment]
There's also this on the `nix` crate:

https://docs.rs/nix/latest/nix/sys/personality/index.html

But I can still update the `linux-personality` crate if you prefer so.

**Comment by jeandudey** [comment]
I've released `2.0.0` of the crate in any case.

**Comment by TornaxO7** [comment]
Awesome!

![peepoAwesome](https://github.com/user-attachments/assets/8b820166-721d-40c8-8f9b-a8e7263166e5)

**Comment by orhun** [comment]
Wow, thank you @jeandudey!
