### ISSUE TITLE
White Bold texts are hidden in Light Theme.

### ISSUE THREAD

**Issue by eminfedar** [orhun/binsider#8]
**Describe the bug**

I use GNOME with light appearance, no additional themes.

White Texts in dark mode are not shown in light mode. Probably coloring issue.

**To reproduce**

1. `cargo install binsider` on a Gnome distro with Light Theme.
2. Run `binsider` in Gnome Terminal.
3. White texts are not showing in Light mode.

**Expected behavior**

White Bold texts in dark theme should become Black Bold texts in light theme.

**Screenshots / Logs**

![image](https://github.com/user-attachments/assets/f24d532e-56b6-4776-b4fd-3d281ac8bc5c)

**Software information**

- Operating system: Pardus 23 GNU/Linux
- Rust version: rustc 1.79.0
- Project version: 0.1.0

**Additional context**

Thanks for this app.

**Comment by orhun** [comment]
Hello, thanks for reporting!

It should be fixed in #23, can you take a look and let me know?

**Comment by eminfedar** [comment]
Yep it is fixed!
