### ISSUE TITLE
Can't run on M1 macOS

### ISSUE THREAD

**Issue by ixzh** [orhun/binsider#87]
**Describe the bug**

cargo install binsider

**Expected behavior**
compile with no error.  yet got this error:
`Some errors have detailed explanations: E0308, E0425, E0432, E0599.`

**Software information**
- Operating system: macOS
- Rust version: 1.8.2
- Project version: 0.2.1

**Additional context**
`brew install binsider` succesfully, but can't launch it:
`ELF parse error: `Invalid Magic Bytes: [CF, FA, ED, FE]``

**Comment by orhun** [comment]
Are you sure you are running `binsider` on an ELF file? See #20
