### ISSUE TITLE
Corrupted screen on Strings tab

### ISSUE THREAD

**Issue by eminfedar** [orhun/binsider#9]
**Describe the bug**

Screen is getting corrupted when listing Strings from the binary.

**To reproduce**

1. `cargo install binsider`
2. Run `binsider executable-file`
3. Go to `Strings` tab
4. Scroll Down a lot (6-7 pages)
5. Some kind of strings in the binary corrupts the screen.

**Expected behavior**

We should see the strings as characters properly or if they can not be displayed as characters, show them as hexadecimal numbers maybe?

**Screenshots / Logs**

![image](https://github.com/user-attachments/assets/755695d7-e8f8-4b8c-ae78-e0eec9570999)

**Software information**

- Operating system: Pardus 23 GNU/Linux
- Rust version: rustc 1.79.0
- Project version: 0.1.0

**Additional context**

**Comment by orhun** [comment]
Hmm interesting, Is there any chance that you can share this specific binary file for testing? There might be a couple of reasons why this is happening:

- terminal size
- terminal font
- special characters in the string

So I need to investigate further.

**Comment by eminfedar** [comment]
Here is the file I have tried:

[vaktisalah-gtk-rs.zip](https://github.com/user-attachments/files/16990638/vaktisalah-gtk-rs.zip)

Probably it is because of the special characters. Just scroll down a lot, you will see. Have a nice day :).

**Comment by orhun** [comment]
I have a potential fix for this here: #28 - can you check and let me know?

I might apply the same fix for dynamic analysis tab since I recall a similar issue in the syscalls as well.

**Comment by eminfedar** [comment]
solved!
